version: '3.1'

services:
  api-server:
    build: ./server
    restart: always
    container_name: expressapp
    ports:
      - 5000:5000
    networks:
      - developers-app
    depends_on:
      - mongo
      - redis
    environment:
      MONGODB_URL: 'mongodb://root:example@mongo:27017/'
      REDIS_URL: 'redis://redis:6379/'

  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    networks:
      - developers-app
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: developers

  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    networks:
      - developers-app

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - developers-app
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: example
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

networks:
  developers-app:
    driver: bridge
